/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sz_jvm_NativeMethod */

#ifndef _Included_com_sz_jvm_NativeMethod
#define _Included_com_sz_jvm_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif


    /*
     * Class:     com_sz_jvm_NativeMethod
     * Method:    world
     * Signature: ()V
     */
JNIEXPORT void JNICALL Java_com_sz_jvm_JavaThread_start0
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
